"""Regenerate engine/src/casefold.rs from this interpreter's str.casefold.

Run from the repository root with the project's Python:

    .venv/bin/python engine/tools/generate_casefold.py
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CASEFOLD = ROOT / "engine" / "engine" / "src" / "casefold.rs"
PYPRINT = ROOT / "engine" / "engine" / "src" / "pyprint.rs"


def rust_str(text: str) -> str:
    out = ['"']
    for ch in text:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 32 <= code < 127:
            out.append(ch)
        else:
            out.append(f"\\u{{{code:X}}}")
    out.append('"')
    return "".join(out)


def main() -> None:
    rows: list[tuple[int, str]] = []
    for code_point in range(0x110000):
        if 0xD800 <= code_point <= 0xDFFF:
            continue
        folded = chr(code_point).casefold()
        if folded != chr(code_point):
            rows.append((code_point, folded))
    lines = [
        "// Full Unicode case fold, generated from this machine's Python str.casefold.",
        "// Characters that fold to themselves are absent.",
        "// Regenerate with engine/tools/generate_casefold.py.",
        "",
        "pub fn casefold(text: &str) -> String {",
        "    let mut out = String::with_capacity(text.len());",
        "    for ch in text.chars() {",
        "        match lookup(ch as u32) {",
        "            Some(folded) => out.push_str(folded),",
        "            None => out.push(ch),",
        "        }",
        "    }",
        "    out",
        "}",
        "",
        "fn lookup(cp: u32) -> Option<&'static str> {",
        "    MAP.binary_search_by_key(&cp, |row| row.0)",
        "        .ok()",
        "        .map(|index| MAP[index].1)",
        "}",
        "",
        "static MAP: &[(u32, &str)] = &[",
    ]
    for code_point, folded in rows:
        lines.append(f"    (0x{code_point:X}, {rust_str(folded)}),")
    lines.append("];")
    lines.append("")
    CASEFOLD.write_text("\n".join(lines))
    print(f"{len(rows)} entries -> {CASEFOLD}")
    write_printable()


def write_printable() -> None:
    ranges: list[tuple[int, int]] = []
    start: int | None = None
    previous = 0
    for code_point in range(0x110000):
        hidden = 0xD800 <= code_point <= 0xDFFF or not chr(code_point).isprintable()
        if hidden:
            if start is None:
                start = code_point
            previous = code_point
        elif start is not None:
            ranges.append((start, previous))
            start = None
    if start is not None:
        ranges.append((start, previous))
    lines = [
        "// Code points Python's str repr escapes. Generated by engine/tools/generate_casefold.py.",
        "",
        "pub(crate) fn py_printable(ch: char) -> bool {",
        "    let cp = ch as u32;",
        "    let index = NONPRINTABLE.partition_point(|range| range.1 < cp);",
        "    index >= NONPRINTABLE.len() || NONPRINTABLE[index].0 > cp",
        "}",
        "",
        "static NONPRINTABLE: &[(u32, u32)] = &[",
    ]
    for begin, end in ranges:
        lines.append(f"    (0x{begin:X}, 0x{end:X}),")
    lines.append("];")
    lines.append("")
    PYPRINT.write_text("\n".join(lines))
    print(f"{len(ranges)} ranges -> {PYPRINT}")


if __name__ == "__main__":
    main()
