"""Turn icons/*.svg (Lucide, ISC) into icons.js, so the page can draw and tint them inline.

    python docs/mockups/look-017/build_icons.py
"""

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
icons = {}
for svg in sorted((HERE / "icons").glob("*.svg")):
    body = svg.read_text(encoding="utf-8")
    inner = re.search(r">(.*)</svg>", body, re.S).group(1)
    icons[svg.stem] = " ".join(inner.split())
(HERE / "icons.js").write_text(
    "// Generated by build_icons.py from icons/*.svg (Lucide, ISC licence). Do not edit.\n"
    f"window.FW_ICONS = {json.dumps(icons, indent=0)};\n",
    encoding="utf-8",
)
print(len(icons), "icons")
