"""Each design's own colourways. A colourway names the colours a layout paints with.

The names carry the contrast rule the audit checks: `x_ink` is text drawn on `x`, `text` and `muted`
are drawn on `surface` and on every `card_`, and `bg_muted` is drawn on `bg`. Every design also offers
"Match my look", which is not listed here because it is derived from the student's palette at run time.
"""

from __future__ import annotations

Colourways = tuple[tuple[str, str, dict[str, str]], ...]


def _tokens(**colours: str) -> dict[str, str]:
    return colours


TIMELINE = (
    (
        # The mock-up's Ruled paper, saved under 0.16's name, with FlexWeek's blue as its accent as the
        # mock-up draws it: a colourway's page stays the same whichever accent the look wears.
        "paper",
        "Ruled paper",
        _tokens(
            bg="#fdfbf7",
            bg_ink="#1a1a1a",
            bg_muted="#5c5750",
            surface="#fffdf9",
            text="#1a1a1a",
            muted="#5c5750",
            accent="#3d6fc4",
            accent_ink="#ffffff",
            line="#cfc7b9",
            danger="#c42b1c",
            danger_ink="#ffffff",
        ),
    ),
    (
        # 0.16's night paper, with FlexWeek's blue on dark for its accent in place of 0.16's white.
        "night",
        "Night",
        _tokens(
            bg="#14161c",
            bg_ink="#eef0f6",
            bg_muted="#aab2c5",
            surface="#1f232d",
            text="#eef0f6",
            muted="#aab2c5",
            accent="#7fa8ff",
            accent_ink="#0b1224",
            line="#333a4a",
            danger="#ff6b7a",
            danger_ink="#14161c",
        ),
    ),
)
MISSION = (
    (
        # The mock-up's signature, near black, with FlexWeek's blue on dark as the mock-up draws it: a
        # colourway's page stays the same whichever accent the look wears.
        "deck",
        "Flight deck",
        _tokens(
            bg="#0b0f14",
            bg_ink="#e6edf5",
            bg_muted="#8d9aab",
            surface="#121821",
            text="#e6edf5",
            muted="#8d9aab",
            accent="#7fa8ff",
            accent_ink="#0b1224",
            line="#2c3846",
            danger="#ff8a7a",
            danger_ink="#0b0f14",
        ),
    ),
    (
        "cyan",
        "Cyan",
        _tokens(
            bg="#070b12",
            bg_ink="#e6eefb",
            bg_muted="#9fb0c8",
            surface="#0d1524",
            text="#e6eefb",
            muted="#9fb0c8",
            accent="#4ee6c4",
            accent_ink="#04101c",
            line="#22304a",
            danger="#ff4d6d",
            danger_ink="#04101c",
        ),
    ),
    (
        "amber",
        "Amber",
        _tokens(
            bg="#0d0a04",
            bg_ink="#fbf1dc",
            bg_muted="#c9b78f",
            surface="#171106",
            text="#fbf1dc",
            muted="#c9b78f",
            accent="#ffb000",
            accent_ink="#1b1400",
            line="#3a2d10",
            danger="#ff6b57",
            danger_ink="#1b0500",
        ),
    ),
    (
        "green",
        "Green",
        _tokens(
            bg="#040b06",
            bg_ink="#e2f7e2",
            bg_muted="#9cc39c",
            surface="#0a160c",
            text="#e2f7e2",
            muted="#9cc39c",
            accent="#6fe36f",
            accent_ink="#041004",
            line="#1b3a1f",
            danger="#ff7a59",
            danger_ink="#1b0500",
        ),
    ),
)
# Bento's colourways paint the hero tile alone, `hero` in `hero_ink` with `hero_muted` for its small
# print; the page and the other tiles are the colourway's own. Indigo is the mock-up's: the light page,
# as 0.17 draws it, with the indigo on the hero only.
BENTO = (
    (
        "indigo",
        "Indigo",
        _tokens(
            bg="#f7f8fa",
            bg_ink="#1e1b4b",
            bg_muted="#4b4a75",
            surface="#ffffff",
            text="#1e1b4b",
            muted="#4b4a75",
            accent="#4f46e5",
            accent_ink="#ffffff",
            line="#e4e7ec",
            danger="#991b1b",
            danger_ink="#ffffff",
            hero="#4338ca",
            hero_ink="#ffffff",
            hero_muted="#e0e7ff",
        ),
    ),
    (
        "sunset",
        "Sunset",
        _tokens(
            bg="#fff4ec",
            bg_ink="#3b1d12",
            bg_muted="#6b4636",
            surface="#ffffff",
            text="#3b1d12",
            muted="#6b4636",
            accent="#c2410c",
            accent_ink="#ffffff",
            line="#fde0cf",
            danger="#9f1239",
            danger_ink="#ffffff",
            hero="#c2410c",
            hero_ink="#ffffff",
            hero_muted="#fff1e6",
        ),
    ),
    (
        "mono",
        "Mono",
        _tokens(
            bg="#f4f4f5",
            bg_ink="#18181b",
            bg_muted="#52525b",
            surface="#ffffff",
            text="#18181b",
            muted="#52525b",
            accent="#18181b",
            accent_ink="#ffffff",
            line="#e4e4e7",
            danger="#991b1b",
            danger_ink="#ffffff",
            hero="#18181b",
            hero_ink="#ffffff",
            hero_muted="#d4d4d8",
        ),
    ),
    (
        "midnight",
        "Midnight",
        _tokens(
            bg="#0b1020",
            bg_ink="#e6ebf5",
            bg_muted="#a2aec9",
            surface="#151b2e",
            text="#e6ebf5",
            muted="#a2aec9",
            accent="#818cf8",
            accent_ink="#0b1020",
            line="#26304a",
            danger="#fca5a5",
            danger_ink="#0b1020",
            hero="#3730a3",
            hero_ink="#ffffff",
            hero_muted="#c7d2fe",
        ),
    ),
)
RETRO = (
    (
        "teal",
        "Teal desktop",
        _tokens(
            bg="#008080",
            bg_ink="#ffffff",
            bg_muted="#ffffff",
            surface="#c0c0c0",
            text="#000000",
            muted="#3a3a3a",
            accent="#000080",
            accent_ink="#ffffff",
            line="#808080",
            danger="#800000",
            danger_ink="#ffffff",
        ),
    ),
    (
        "plum",
        "Plum desktop",
        _tokens(
            bg="#5b2a6e",
            bg_ink="#ffffff",
            bg_muted="#f1e4f7",
            surface="#c0c0c0",
            text="#000000",
            muted="#3a3a3a",
            accent="#4b0082",
            accent_ink="#ffffff",
            line="#808080",
            danger="#800000",
            danger_ink="#ffffff",
        ),
    ),
    (
        "slate",
        "Slate desktop",
        _tokens(
            bg="#3a4a5a",
            bg_ink="#ffffff",
            bg_muted="#e3e9ef",
            surface="#c0c0c0",
            text="#000000",
            muted="#3a3a3a",
            accent="#1f2d3d",
            accent_ink="#ffffff",
            line="#808080",
            danger="#800000",
            danger_ink="#ffffff",
        ),
    ),
)
CLAY = (
    (
        # The mock-up's signature, lavender clay, saved under 0.16's Pastel. It wears the student's accent.
        "pastel",
        "Clay",
        _tokens(
            bg="#efe9fa",
            bg_ink="#221c36",
            bg_muted="#595272",
            surface="#f9f6ff",
            text="#221c36",
            muted="#595272",
            line="#e2daf2",
            danger="#b3261e",
            danger_ink="#ffffff",
        ),
    ),
    (
        "mint",
        "Mint",
        _tokens(
            bg="#ecfbf3",
            bg_ink="#173b2c",
            bg_muted="#2f5a47",
            surface="#ffffff",
            text="#173b2c",
            muted="#2f5a47",
            accent="#173b2c",
            accent_ink="#ffffff",
            line="#cdeedd",
            danger="#9b1c1c",
            danger_ink="#ffffff",
        ),
    ),
    (
        "sunset",
        "Sunset",
        _tokens(
            bg="#fff1e6",
            bg_ink="#4a2313",
            bg_muted="#6e3c26",
            surface="#ffffff",
            text="#4a2313",
            muted="#6e3c26",
            accent="#4a2313",
            accent_ink="#ffffff",
            line="#fbdcc6",
            danger="#9b1c1c",
            danger_ink="#ffffff",
        ),
    ),
    (
        "dusk",
        "Dusk",
        _tokens(
            bg="#17151f",
            bg_ink="#efe9f5",
            bg_muted="#b4a9c4",
            surface="#231f2e",
            text="#efe9f5",
            muted="#b4a9c4",
            accent="#c4b5fd",
            accent_ink="#17151f",
            line="#342e44",
            danger="#fca5a5",
            danger_ink="#17151f",
            cta="#f0abfc",
            cta_ink="#17151f",
        ),
    ),
)
ONE = (
    (
        # 0.16's black page with the student's accent in place of its orange, as 0.17 picked.
        "black",
        "Poster",
        _tokens(
            bg="#000000",
            bg_ink="#ffffff",
            bg_muted="#a3a3a3",
            surface="#141414",
            text="#ffffff",
            muted="#a3a3a3",
            line="#3d3d3d",
            danger="#ff4d6d",
            danger_ink="#000000",
        ),
    ),
    (
        "paper",
        "Paper and ink",
        _tokens(
            bg="#f7f1e3",
            bg_ink="#1c1917",
            bg_muted="#57534e",
            surface="#f7f1e3",
            text="#1c1917",
            muted="#57534e",
            accent="#9a3412",
            accent_ink="#ffffff",
            line="#cfc6b2",
            danger="#a3003c",
            danger_ink="#ffffff",
        ),
    ),
)
DIAL = (
    (
        # 0.16's navy, refined as 0.17 picked, and saved under its old name. It wears the student's accent.
        "midnight",
        "Night",
        _tokens(
            bg="#0b0f1d",
            bg_ink="#e7eaf6",
            bg_muted="#9ea6c4",
            surface="#141a2e",
            text="#e7eaf6",
            muted="#9ea6c4",
            line="#343c5e",
            danger="#ff8a7a",
            danger_ink="#0b0f1d",
        ),
    ),
    (
        "daylight",
        "Daylight",
        _tokens(
            bg="#f4f6fb",
            bg_ink="#111827",
            bg_muted="#4b5563",
            surface="#ffffff",
            text="#111827",
            muted="#4b5563",
            accent="#3730a3",
            accent_ink="#ffffff",
            line="#d5dbea",
            danger="#b91c1c",
            danger_ink="#ffffff",
        ),
    ),
)
